package isilimageprocessing.Dialogues;

public class JDialogFiltrageLineaireGlobal extends javax.swing.JDialog {

    private int frequenceDeCoupure;
    private int ordre;
    
    private boolean filled;
    
    
    /**
     * Creates new form NewJDialogFiltrageLineaire
     * @param parent
     * @param modal
     * @param hasOrdre
     */
    public JDialogFiltrageLineaireGlobal(java.awt.Frame parent, boolean modal, boolean hasOrdre) {
        super(parent, modal);
        
        this.frequenceDeCoupure = 0;
        this.ordre = 0;
        
        initComponents();
        
        this.jSpinnerOrdre.setEnabled(hasOrdre);
        
        this.filled = false;
    }
    
    public int getFrequenceDeCoupure(){
        return this.frequenceDeCoupure;
    }
    
    public int getOrdre(){
        return this.ordre;
    }
    
    public boolean isFilled(){
        return this.filled;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelCoupure = new javax.swing.JLabel();
        jLabelOrdre = new javax.swing.JLabel();
        jSpinnerCoupure = new javax.swing.JSpinner();
        jSpinnerOrdre = new javax.swing.JSpinner();
        jButtonOK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Information");
        setResizable(false);

        jLabelCoupure.setText("Coupure");

        jLabelOrdre.setText("Ordre");

        jSpinnerCoupure.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerCoupureStateChanged(evt);
            }
        });

        jSpinnerOrdre.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSpinnerOrdreStateChanged(evt);
            }
        });

        jButtonOK.setText("OK");
        jButtonOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelCoupure, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelOrdre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jSpinnerOrdre, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                    .addComponent(jSpinnerCoupure))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(87, Short.MAX_VALUE)
                .addComponent(jButtonOK)
                .addGap(78, 78, 78))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCoupure)
                    .addComponent(jSpinnerCoupure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSpinnerOrdre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelOrdre))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jButtonOK)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSpinnerCoupureStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerCoupureStateChanged
        this.frequenceDeCoupure = (int) this.jSpinnerCoupure.getValue();
    }//GEN-LAST:event_jSpinnerCoupureStateChanged

    private void jSpinnerOrdreStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSpinnerOrdreStateChanged
        this.ordre = (int) this.jSpinnerOrdre.getValue();
    }//GEN-LAST:event_jSpinnerOrdreStateChanged

    private void jButtonOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonOKActionPerformed
        this.filled = true;
        this.dispose();
    }//GEN-LAST:event_jButtonOKActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonOK;
    private javax.swing.JLabel jLabelCoupure;
    private javax.swing.JLabel jLabelOrdre;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSpinner jSpinnerCoupure;
    private javax.swing.JSpinner jSpinnerOrdre;
    // End of variables declaration//GEN-END:variables
}
