/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package isilimageprocessing.Dialogues;

/**
 *
 * @author Fred
 */
public class JDialogAfficheInformationImage extends javax.swing.JDialog {

    /**
     * Creates new form JDialogAfficheInformationImage
     */
    public JDialogAfficheInformationImage(java.awt.Frame parent, boolean modal, int minimum, int maximum, int luminance, double contraste1, double contraste2) {
        super(parent, modal);
        initComponents();
        
        // Set values for labels
        jLabelMiniumValue.setText(String.valueOf(minimum));
        jLabelMaximumValue.setText(String.valueOf(maximum));
        jLabelLuminanceValue.setText(String.valueOf(luminance));
        jLabelContraste1Value.setText(String.format("%.2f", contraste1));
        jLabelContraste2Value.setText(String.format("%.2f", contraste2));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelMinimum = new javax.swing.JLabel();
        jLabelMaximum = new javax.swing.JLabel();
        jLabelLuminance = new javax.swing.JLabel();
        jLabelContraste1 = new javax.swing.JLabel();
        jLabelContraste2 = new javax.swing.JLabel();
        jLabelMiniumValue = new javax.swing.JLabel();
        jLabelMaximumValue = new javax.swing.JLabel();
        jLabelLuminanceValue = new javax.swing.JLabel();
        jLabelContraste1Value = new javax.swing.JLabel();
        jLabelContraste2Value = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Informations sur l'image");
        setResizable(false);

        jLabelMinimum.setText("Minimum");

        jLabelMaximum.setText("Maximum");

        jLabelLuminance.setText("Luminance");

        jLabelContraste1.setText("Contraste1");

        jLabelContraste2.setText("Contraste2");

        jLabelMiniumValue.setText("/");

        jLabelMaximumValue.setText("/");

        jLabelLuminanceValue.setText("/");

        jLabelContraste1Value.setText("/");

        jLabelContraste2Value.setText("/");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(66, 66, 66)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelContraste2, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMaximum, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMinimum, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelLuminance, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelContraste1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelMiniumValue, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMaximumValue, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelContraste1Value, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelContraste2Value, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelLuminanceValue, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(76, 76, 76)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelMinimum)
                    .addComponent(jLabelMiniumValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMaximum, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelMaximumValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLuminance)
                    .addComponent(jLabelLuminanceValue))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelContraste1)
                    .addComponent(jLabelContraste1Value))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelContraste2)
                    .addComponent(jLabelContraste2Value))
                .addContainerGap(72, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabelContraste1;
    private javax.swing.JLabel jLabelContraste1Value;
    private javax.swing.JLabel jLabelContraste2;
    private javax.swing.JLabel jLabelContraste2Value;
    private javax.swing.JLabel jLabelLuminance;
    private javax.swing.JLabel jLabelLuminanceValue;
    private javax.swing.JLabel jLabelMaximum;
    private javax.swing.JLabel jLabelMaximumValue;
    private javax.swing.JLabel jLabelMinimum;
    private javax.swing.JLabel jLabelMiniumValue;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
