package isilimageprocessing;

import CImage.*;
import CImage.Exceptions.*;
import CImage.Observers.*;
import CImage.Observers.Events.*;
import ImageProcessing.Contours.ContoursLineaire;
import ImageProcessing.Complexe.MatriceComplexe;
import ImageProcessing.Fourier.Fourier;
import ImageProcessing.Histogramme.Histogramme;
import ImageProcessing.Lineaire.FiltrageLineaireGlobal;
import ImageProcessing.Lineaire.FiltrageLineaireLocal;
import ImageProcessing.NonLineaire.MorphoElementaire;
import ImageProcessing.NonLineaire.MorphoComplexe;
import ImageProcessing.Utils.Utils;
import isilimageprocessing.Dialogues.*;
import java.awt.*;
import java.io.*;
import javax.swing.*;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.axis.ValueAxis;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.chart.plot.XYPlot;
import org.jfree.data.xy.XYSeries;
import org.jfree.data.xy.XYSeriesCollection;
import javax.swing.JToggleButton;
import javax.swing.JToolBar;
import java.awt.event.ActionEvent;
import javax.swing.AbstractAction;
import javax.swing.KeyStroke;


public class IsilImageProcessing extends javax.swing.JFrame implements ClicListener,SelectLigneListener,SelectRectListener,SelectRectFillListener,SelectCercleListener,SelectCercleFillListener 
{
    private CImageRGB imageRGB;
    private CImageNG  imageNG;
    
    private JLabelBeanCImage observer;
    private Color couleurPinceauRGB;
    private int   couleurPinceauNG;
    
    private CImage liftedImage = null;
    private int liftedFromIndex = -1;
    
    private enum GridMode { SELECT, MOVE }
    private GridMode currentGridMode = GridMode.SELECT;
    private CImage resultImage;
    
    private JTextField inputField;

    
    public IsilImageProcessing() 
    {
        initComponents();
        
        // ANTOINE WAS HERE
        panelResult.setLayout(new BorderLayout());
        panelResult.add(resultPanel, BorderLayout.CENTER);
        panelResult.revalidate();

        setupImageGridSlots();
        
        resultPanel.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mousePressed(java.awt.event.MouseEvent evt) {
                if (currentGridMode == GridMode.MOVE && resultImage != null) {
                    clearAllSelections();
                    liftedImage = resultImage;
                    liftedFromIndex = -1;
                    resultPanel.setBorder(BorderFactory.createLineBorder(Color.ORANGE, 3));
                }
            }
        });

        
        // Add move/select toggle manually
        JCheckBoxMenuItem toggleMoveMode = new JCheckBoxMenuItem("Mode Déplacement");
        toggleMoveMode.addActionListener(e -> {
            currentGridMode = toggleMoveMode.isSelected() ? GridMode.MOVE : GridMode.SELECT;
        });
        jMenuImage.add(toggleMoveMode);  // add it to the Image menu (or any other menu)

        setupModeToggleUI();
        
        // IT'S OVER
        
        imageRGB = null;
        imageNG  = null;
        
        
        jMenuDessiner.setEnabled(false);
        jMenuFourier.setEnabled(false);
        jMenuHistogramme.setEnabled(false);
        jMenuLineaire.setEnabled(false);
        jMenuTraitement.setEnabled(false);
        jMenuContours.setEnabled(false);

        
        couleurPinceauRGB = Color.BLACK;
        couleurPinceauNG = 0;
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroupDessiner = new javax.swing.ButtonGroup();
        panelResult = new javax.swing.JPanel();
        resultPanel = new javax.swing.JLabel();
        panelGrid = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuImage = new javax.swing.JMenu();
        jMenuNouvelle = new javax.swing.JMenu();
        jMenuItemNouvelleRGB = new javax.swing.JMenuItem();
        jMenuItemNouvelleNG = new javax.swing.JMenuItem();
        jMenuOuvrir = new javax.swing.JMenu();
        jMenuItemOuvrirRGB = new javax.swing.JMenuItem();
        jMenuItemOuvrirNG = new javax.swing.JMenuItem();
        jMenuItemEnregistrerSous = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        jMenuQuitter = new javax.swing.JMenuItem();
        jMenuDessiner = new javax.swing.JMenu();
        jMenuItemCouleurPinceau = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JSeparator();
        jCheckBoxMenuItemDessinerPixel = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItemDessinerLigne = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItemDessinerRectangle = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItemDessinerRectanglePlein = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItemDessinerCercle = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItemDessinerCerclePlein = new javax.swing.JCheckBoxMenuItem();
        jMenuFourier = new javax.swing.JMenu();
        jMenuFourierAfficher = new javax.swing.JMenu();
        jMenuItemFourierAfficherModule = new javax.swing.JMenuItem();
        jMenuItemFourierAfficherPhase = new javax.swing.JMenuItem();
        jMenuItemFourierAfficherPartieReelle = new javax.swing.JMenuItem();
        jMenuItemFourierAfficherPartieImaginaire = new javax.swing.JMenuItem();
        jMenuHistogramme = new javax.swing.JMenu();
        jMenuHistogrammeAfficher = new javax.swing.JMenuItem();
        jMenuAfficherParametresImage = new javax.swing.JMenuItem();
        jMenuLineaire = new javax.swing.JMenu();
        jMenuLineaireGlobal = new javax.swing.JMenu();
        jMenuItemFiltrageLineaireGlobalPasseBas = new javax.swing.JMenuItem();
        jMenuItemFiltrageLineaireGlobalPasseHaut = new javax.swing.JMenuItem();
        jMenuItemFiltrageLineaireGlobalPasseBasButterworth = new javax.swing.JMenuItem();
        jMenuItemFiltrageLineaireGlobalPasseHautButterworth = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenuItemFiltrageLineaireLocalFiltrageConvolution = new javax.swing.JMenuItem();
        jMenuItemFiltrageLineaireLocalFiltrageMoyenneur = new javax.swing.JMenuItem();
        jMenuTraitement = new javax.swing.JMenu();
        jMenuTraitementElementaire = new javax.swing.JMenu();
        jMenuItemTraitementLineaireMorphologieElementaireErosion = new javax.swing.JMenuItem();
        jMenuItemTraitementLineaireMorphologieElementaireDilatation = new javax.swing.JMenuItem();
        jMenuItemTraitementLineaireMorphologieElementaireOuverture = new javax.swing.JMenuItem();
        jMenuItemTraitementLineaireMorphologieElementaireFermeture = new javax.swing.JMenuItem();
        jMenuTraitementComplexe = new javax.swing.JMenu();
        jMenuItemTraitementLineaireMorphologieComplexeDilatationGeodesique = new javax.swing.JMenuItem();
        jMenuItemTraitementLineaireMorphologieComplexeReconstructionGeodesique = new javax.swing.JMenuItem();
        jMenuItemTraitementLineaireMorphologieComplexeFiltreMedian = new javax.swing.JMenuItem();
        jMenuContours = new javax.swing.JMenu();
        jMenuContoursLineaire = new javax.swing.JMenu();
        jMenuItemContoursLineairePrewitt = new javax.swing.JMenuItem();
        jMenuItemContoursLineaireSobel = new javax.swing.JMenuItem();
        jMenuItemContoursLineaireLaplacien4 = new javax.swing.JMenuItem();
        jMenuItemContoursLineaireLaplacien8 = new javax.swing.JMenuItem();
        jMenuContoursNonLineaire = new javax.swing.JMenu();
        jMenuItemContoursNonLineaireErosion = new javax.swing.JMenuItem();
        jMenuItemContoursNonLineaireDilatation = new javax.swing.JMenuItem();
        jMenuItemContoursNonLineaireBeucher = new javax.swing.JMenuItem();
        jMenuItemContoursNonLineaireLaplacien = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Isil Image Processing");
        getContentPane().setLayout(new java.awt.BorderLayout());

        panelResult.setBackground(new java.awt.Color(255, 51, 51));
        panelResult.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        panelResult.setPreferredSize(new java.awt.Dimension(150, 100));
        panelResult.add(resultPanel);

        getContentPane().add(panelResult, java.awt.BorderLayout.EAST);

        panelGrid.setBackground(new java.awt.Color(102, 51, 255));
        panelGrid.setBorder(javax.swing.BorderFactory.createLineBorder(null));
        panelGrid.setLayout(new java.awt.GridLayout(3, 3));

        jLabel9.setText("jLabel9");
        panelGrid.add(jLabel9);

        jLabel8.setText("jLabel8");
        panelGrid.add(jLabel8);

        jLabel7.setText("jLabel7");
        panelGrid.add(jLabel7);

        jLabel6.setText("jLabel6");
        panelGrid.add(jLabel6);

        jLabel5.setText("jLabel5");
        panelGrid.add(jLabel5);

        jLabel4.setText("jLabel4");
        panelGrid.add(jLabel4);

        jLabel3.setText("jLabel3");
        panelGrid.add(jLabel3);

        jLabel2.setText("jLabel2");
        panelGrid.add(jLabel2);

        jLabel1.setText("jLabel1");
        panelGrid.add(jLabel1);

        getContentPane().add(panelGrid, java.awt.BorderLayout.CENTER);

        jMenuImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Net_13_p1.jpg"))); // NOI18N
        jMenuImage.setText("Image");

        jMenuNouvelle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/File_65_p3.jpg"))); // NOI18N
        jMenuNouvelle.setText("Nouvelle");

        jMenuItemNouvelleRGB.setText("Image RGB");
        jMenuItemNouvelleRGB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNouvelleRGBActionPerformed(evt);
            }
        });
        jMenuNouvelle.add(jMenuItemNouvelleRGB);

        jMenuItemNouvelleNG.setText("Image NG");
        jMenuItemNouvelleNG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemNouvelleNGActionPerformed(evt);
            }
        });
        jMenuNouvelle.add(jMenuItemNouvelleNG);

        jMenuImage.add(jMenuNouvelle);

        jMenuOuvrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Folder_036_p3.jpg"))); // NOI18N
        jMenuOuvrir.setText("Ouvrir");

        jMenuItemOuvrirRGB.setText("Image RGB");
        jMenuItemOuvrirRGB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemOuvrirRGBActionPerformed(evt);
            }
        });
        jMenuOuvrir.add(jMenuItemOuvrirRGB);

        jMenuItemOuvrirNG.setText("Image NG");
        jMenuItemOuvrirNG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemOuvrirNGActionPerformed(evt);
            }
        });
        jMenuOuvrir.add(jMenuItemOuvrirNG);

        jMenuImage.add(jMenuOuvrir);

        jMenuItemEnregistrerSous.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/DD_27_p3.jpg"))); // NOI18N
        jMenuItemEnregistrerSous.setText("Enregistrer sous...");
        jMenuItemEnregistrerSous.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEnregistrerSousActionPerformed(evt);
            }
        });
        jMenuImage.add(jMenuItemEnregistrerSous);
        jMenuImage.add(jSeparator1);

        jMenuQuitter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/CP_59_p3.jpg"))); // NOI18N
        jMenuQuitter.setText("Quitter");
        jMenuQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuQuitterActionPerformed(evt);
            }
        });
        jMenuImage.add(jMenuQuitter);

        jMenuBar1.add(jMenuImage);

        jMenuDessiner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Display_28_p1.jpg"))); // NOI18N
        jMenuDessiner.setText("Dessiner");

        jMenuItemCouleurPinceau.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/Display_14_p3.jpg"))); // NOI18N
        jMenuItemCouleurPinceau.setText("Couleur");
        jMenuItemCouleurPinceau.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCouleurPinceauActionPerformed(evt);
            }
        });
        jMenuDessiner.add(jMenuItemCouleurPinceau);
        jMenuDessiner.add(jSeparator2);

        jCheckBoxMenuItemDessinerPixel.setText("Pixel");
        jCheckBoxMenuItemDessinerPixel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItemDessinerPixelActionPerformed(evt);
            }
        });
        jMenuDessiner.add(jCheckBoxMenuItemDessinerPixel);

        jCheckBoxMenuItemDessinerLigne.setText("Ligne");
        jCheckBoxMenuItemDessinerLigne.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItemDessinerLigneActionPerformed(evt);
            }
        });
        jMenuDessiner.add(jCheckBoxMenuItemDessinerLigne);

        jCheckBoxMenuItemDessinerRectangle.setText("Rectangle");
        jCheckBoxMenuItemDessinerRectangle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItemDessinerRectangleActionPerformed(evt);
            }
        });
        jMenuDessiner.add(jCheckBoxMenuItemDessinerRectangle);

        jCheckBoxMenuItemDessinerRectanglePlein.setText("Rectangle plein");
        jCheckBoxMenuItemDessinerRectanglePlein.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItemDessinerRectanglePleinActionPerformed(evt);
            }
        });
        jMenuDessiner.add(jCheckBoxMenuItemDessinerRectanglePlein);

        jCheckBoxMenuItemDessinerCercle.setText("Cercle");
        jCheckBoxMenuItemDessinerCercle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItemDessinerCercleActionPerformed(evt);
            }
        });
        jMenuDessiner.add(jCheckBoxMenuItemDessinerCercle);

        jCheckBoxMenuItemDessinerCerclePlein.setText("Cercle plein");
        jCheckBoxMenuItemDessinerCerclePlein.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItemDessinerCerclePleinActionPerformed(evt);
            }
        });
        jMenuDessiner.add(jCheckBoxMenuItemDessinerCerclePlein);

        jMenuBar1.add(jMenuDessiner);

        jMenuFourier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/CP_51_p1.jpg"))); // NOI18N
        jMenuFourier.setText("Fourier");

        jMenuFourierAfficher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/CP_51_p3.jpg"))); // NOI18N
        jMenuFourierAfficher.setText("Afficher");

        jMenuItemFourierAfficherModule.setText("Module");
        jMenuItemFourierAfficherModule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFourierAfficherModuleActionPerformed(evt);
            }
        });
        jMenuFourierAfficher.add(jMenuItemFourierAfficherModule);

        jMenuItemFourierAfficherPhase.setText("Phase");
        jMenuItemFourierAfficherPhase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFourierAfficherPhaseActionPerformed(evt);
            }
        });
        jMenuFourierAfficher.add(jMenuItemFourierAfficherPhase);

        jMenuItemFourierAfficherPartieReelle.setText("Partie Reelle");
        jMenuItemFourierAfficherPartieReelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFourierAfficherPartieReelleActionPerformed(evt);
            }
        });
        jMenuFourierAfficher.add(jMenuItemFourierAfficherPartieReelle);

        jMenuItemFourierAfficherPartieImaginaire.setText("Partie Imaginaire");
        jMenuItemFourierAfficherPartieImaginaire.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFourierAfficherPartieImaginaireActionPerformed(evt);
            }
        });
        jMenuFourierAfficher.add(jMenuItemFourierAfficherPartieImaginaire);

        jMenuFourier.add(jMenuFourierAfficher);

        jMenuBar1.add(jMenuFourier);

        jMenuHistogramme.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/report_48_hot.jpg"))); // NOI18N
        jMenuHistogramme.setText("Histogramme");

        jMenuHistogrammeAfficher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/report_32_hot.jpg"))); // NOI18N
        jMenuHistogrammeAfficher.setText("Afficher");
        jMenuHistogrammeAfficher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuHistogrammeAfficherActionPerformed(evt);
            }
        });
        jMenuHistogramme.add(jMenuHistogrammeAfficher);

        jMenuAfficherParametresImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/metadata_32.png"))); // NOI18N
        jMenuAfficherParametresImage.setText("Afficher les paramètres de l'image");
        jMenuAfficherParametresImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuAfficherParametresImageActionPerformed(evt);
            }
        });
        jMenuHistogramme.add(jMenuAfficherParametresImage);

        jMenuBar1.add(jMenuHistogramme);

        jMenuLineaire.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/filtrage_48.png"))); // NOI18N
        jMenuLineaire.setText("Filtrage Lineaire");

        jMenuLineaireGlobal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/filtrage_32.png"))); // NOI18N
        jMenuLineaireGlobal.setText("Global");

        jMenuItemFiltrageLineaireGlobalPasseBas.setText("Filtrage passe-bas");
        jMenuItemFiltrageLineaireGlobalPasseBas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFiltrageLineaireGlobalPasseBasActionPerformed(evt);
            }
        });
        jMenuLineaireGlobal.add(jMenuItemFiltrageLineaireGlobalPasseBas);

        jMenuItemFiltrageLineaireGlobalPasseHaut.setText("Filtrage passe-haut");
        jMenuItemFiltrageLineaireGlobalPasseHaut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFiltrageLineaireGlobalPasseHautActionPerformed(evt);
            }
        });
        jMenuLineaireGlobal.add(jMenuItemFiltrageLineaireGlobalPasseHaut);

        jMenuItemFiltrageLineaireGlobalPasseBasButterworth.setText("Filtrage passe-bas butterworth");
        jMenuItemFiltrageLineaireGlobalPasseBasButterworth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFiltrageLineaireGlobalPasseBasButterworthActionPerformed(evt);
            }
        });
        jMenuLineaireGlobal.add(jMenuItemFiltrageLineaireGlobalPasseBasButterworth);

        jMenuItemFiltrageLineaireGlobalPasseHautButterworth.setText("Filtrage passe-haut butterworth");
        jMenuItemFiltrageLineaireGlobalPasseHautButterworth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFiltrageLineaireGlobalPasseHautButterworthActionPerformed(evt);
            }
        });
        jMenuLineaireGlobal.add(jMenuItemFiltrageLineaireGlobalPasseHautButterworth);

        jMenuLineaire.add(jMenuLineaireGlobal);

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/filtrage_32.png"))); // NOI18N
        jMenu1.setText("Local");

        jMenuItemFiltrageLineaireLocalFiltrageConvolution.setText("Filtrage convolution");
        jMenuItemFiltrageLineaireLocalFiltrageConvolution.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFiltrageLineaireLocalFiltrageConvolutionActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemFiltrageLineaireLocalFiltrageConvolution);

        jMenuItemFiltrageLineaireLocalFiltrageMoyenneur.setText("Filtrage moyenneur");
        jMenuItemFiltrageLineaireLocalFiltrageMoyenneur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemFiltrageLineaireLocalFiltrageMoyenneurActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItemFiltrageLineaireLocalFiltrageMoyenneur);

        jMenuLineaire.add(jMenu1);

        jMenuBar1.add(jMenuLineaire);

        jMenuTraitement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/traitement_48.png"))); // NOI18N
        jMenuTraitement.setText("Traitement Lineaire");
        jMenuTraitement.setToolTipText("");

        jMenuTraitementElementaire.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/traitement_32.png"))); // NOI18N
        jMenuTraitementElementaire.setText("Morphologie Elementaire");

        jMenuItemTraitementLineaireMorphologieElementaireErosion.setText("Erosion");
        jMenuItemTraitementLineaireMorphologieElementaireErosion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTraitementLineaireMorphologieElementaireErosionActionPerformed(evt);
            }
        });
        jMenuTraitementElementaire.add(jMenuItemTraitementLineaireMorphologieElementaireErosion);

        jMenuItemTraitementLineaireMorphologieElementaireDilatation.setText("Dilatation");
        jMenuItemTraitementLineaireMorphologieElementaireDilatation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTraitementLineaireMorphologieElementaireDilatationActionPerformed(evt);
            }
        });
        jMenuTraitementElementaire.add(jMenuItemTraitementLineaireMorphologieElementaireDilatation);

        jMenuItemTraitementLineaireMorphologieElementaireOuverture.setText("Ouverture");
        jMenuItemTraitementLineaireMorphologieElementaireOuverture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTraitementLineaireMorphologieElementaireOuvertureActionPerformed(evt);
            }
        });
        jMenuTraitementElementaire.add(jMenuItemTraitementLineaireMorphologieElementaireOuverture);

        jMenuItemTraitementLineaireMorphologieElementaireFermeture.setText("Fermeture");
        jMenuItemTraitementLineaireMorphologieElementaireFermeture.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTraitementLineaireMorphologieElementaireFermetureActionPerformed(evt);
            }
        });
        jMenuTraitementElementaire.add(jMenuItemTraitementLineaireMorphologieElementaireFermeture);

        jMenuTraitement.add(jMenuTraitementElementaire);

        jMenuTraitementComplexe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/traitement_32.png"))); // NOI18N
        jMenuTraitementComplexe.setText("Morphologie Complexe");
        jMenuTraitementComplexe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuTraitementComplexeActionPerformed(evt);
            }
        });

        jMenuItemTraitementLineaireMorphologieComplexeDilatationGeodesique.setText("Dilatation Geodesique");
        jMenuItemTraitementLineaireMorphologieComplexeDilatationGeodesique.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTraitementLineaireMorphologieComplexeDilatationGeodesiqueActionPerformed(evt);
            }
        });
        jMenuTraitementComplexe.add(jMenuItemTraitementLineaireMorphologieComplexeDilatationGeodesique);

        jMenuItemTraitementLineaireMorphologieComplexeReconstructionGeodesique.setText("Reconstruction Geodesique");
        jMenuItemTraitementLineaireMorphologieComplexeReconstructionGeodesique.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTraitementLineaireMorphologieComplexeReconstructionGeodesiqueActionPerformed(evt);
            }
        });
        jMenuTraitementComplexe.add(jMenuItemTraitementLineaireMorphologieComplexeReconstructionGeodesique);

        jMenuItemTraitementLineaireMorphologieComplexeFiltreMedian.setText("Filtre Median");
        jMenuItemTraitementLineaireMorphologieComplexeFiltreMedian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemTraitementLineaireMorphologieComplexeFiltreMedianActionPerformed(evt);
            }
        });
        jMenuTraitementComplexe.add(jMenuItemTraitementLineaireMorphologieComplexeFiltreMedian);

        jMenuTraitement.add(jMenuTraitementComplexe);

        jMenuBar1.add(jMenuTraitement);

        jMenuContours.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/contours_48.png"))); // NOI18N
        jMenuContours.setText("Contours");

        jMenuContoursLineaire.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/contours_32.png"))); // NOI18N
        jMenuContoursLineaire.setText("Linéaire");

        jMenuItemContoursLineairePrewitt.setText("Prewitt");
        jMenuItemContoursLineairePrewitt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemContoursLineairePrewittActionPerformed(evt);
            }
        });
        jMenuContoursLineaire.add(jMenuItemContoursLineairePrewitt);

        jMenuItemContoursLineaireSobel.setText("Sobel");
        jMenuItemContoursLineaireSobel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemContoursLineaireSobelActionPerformed(evt);
            }
        });
        jMenuContoursLineaire.add(jMenuItemContoursLineaireSobel);

        jMenuItemContoursLineaireLaplacien4.setText("Laplacien 4");
        jMenuItemContoursLineaireLaplacien4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemContoursLineaireLaplacien4ActionPerformed(evt);
            }
        });
        jMenuContoursLineaire.add(jMenuItemContoursLineaireLaplacien4);

        jMenuItemContoursLineaireLaplacien8.setText("Laplacien 8");
        jMenuItemContoursLineaireLaplacien8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemContoursLineaireLaplacien8ActionPerformed(evt);
            }
        });
        jMenuContoursLineaire.add(jMenuItemContoursLineaireLaplacien8);

        jMenuContours.add(jMenuContoursLineaire);

        jMenuContoursNonLineaire.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icones/contours_32.png"))); // NOI18N
        jMenuContoursNonLineaire.setText("Non-linéaire");

        jMenuItemContoursNonLineaireErosion.setText("Erosion");
        jMenuItemContoursNonLineaireErosion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemContoursNonLineaireErosionActionPerformed(evt);
            }
        });
        jMenuContoursNonLineaire.add(jMenuItemContoursNonLineaireErosion);

        jMenuItemContoursNonLineaireDilatation.setText("Dilatation");
        jMenuItemContoursNonLineaireDilatation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemContoursNonLineaireDilatationActionPerformed(evt);
            }
        });
        jMenuContoursNonLineaire.add(jMenuItemContoursNonLineaireDilatation);

        jMenuItemContoursNonLineaireBeucher.setText("Beucher");
        jMenuItemContoursNonLineaireBeucher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemContoursNonLineaireBeucherActionPerformed(evt);
            }
        });
        jMenuContoursNonLineaire.add(jMenuItemContoursNonLineaireBeucher);

        jMenuItemContoursNonLineaireLaplacien.setText("Laplacien");
        jMenuItemContoursNonLineaireLaplacien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemContoursNonLineaireLaplacienActionPerformed(evt);
            }
        });
        jMenuContoursNonLineaire.add(jMenuItemContoursNonLineaireLaplacien);

        jMenuContours.add(jMenuContoursNonLineaire);

        jMenuBar1.add(jMenuContours);

        setJMenuBar(jMenuBar1);

        setSize(new java.awt.Dimension(1104, 718));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    // ANTOINE WAS HERE
    private void showResultImage(CImage result) {
        this.resultImage = result;  // Save the actual image shown in result panel

        Image img = result.getImage();
        Image scaled = img.getScaledInstance(resultPanel.getWidth(), resultPanel.getHeight(), Image.SCALE_SMOOTH);
        resultPanel.setIcon(new ImageIcon(scaled));
        resultPanel.revalidate();
        resultPanel.repaint();
    }

    private void jMenuHistogrammeAfficherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuHistogrammeAfficherActionPerformed
        int histo[];
        try 
        {
            int f_int[][] = imageNG.getMatrice();
            histo = Histogramme.Histogramme256(f_int);
        } 
        catch (CImageNGException ex) 
        {
            System.out.println("Erreur CImageNG : " + ex.getMessage());
            return;
        }
        
        // Creation du dataset
        XYSeries serie = new XYSeries("Histo");
        for(int i=0 ; i<256 ; i++) serie.add(i,histo[i]);
        XYSeriesCollection dataset = new XYSeriesCollection();
        dataset.addSeries(serie);
        
        // Creation du chart
        JFreeChart chart = ChartFactory.createHistogram("Histogramme","Niveaux de gris","Nombre de pixels",dataset,PlotOrientation.VERTICAL,false,false,false);

        XYPlot plot = (XYPlot)chart.getXYPlot();
        ValueAxis axeX = plot.getDomainAxis();
        axeX.setRange(0,255);
        plot.setDomainAxis(axeX);
        
        // Creation d'une frame
        ChartFrame frame = new ChartFrame("Histogramme de l'image",chart);
        frame.pack();
        frame.setVisible(true);
    }//GEN-LAST:event_jMenuHistogrammeAfficherActionPerformed

    private void activeMenusNG()
    {
        jMenuDessiner.setEnabled(true);
        jMenuFourier.setEnabled(true);
        jMenuHistogramme.setEnabled(true);
        jMenuLineaire.setEnabled(true);
        jMenuTraitement.setEnabled(true);
        jMenuContours.setEnabled(true);
    }
    
    private void activeMenusRGB()
    {
        jMenuDessiner.setEnabled(true);
        jMenuFourier.setEnabled(false);
        jMenuHistogramme.setEnabled(false);
        jMenuLineaire.setEnabled(false);
        jMenuTraitement.setEnabled(false);
        jMenuContours.setEnabled(false);
    }
    
    private void jCheckBoxMenuItemDessinerCerclePleinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItemDessinerCerclePleinActionPerformed
        if (!jCheckBoxMenuItemDessinerCerclePlein.isSelected()) observer.setMode(JLabelBeanCImage.INACTIF);
        else
        {
            jCheckBoxMenuItemDessinerPixel.setSelected(false);
            jCheckBoxMenuItemDessinerLigne.setSelected(false);
            jCheckBoxMenuItemDessinerRectangle.setSelected(false);
            jCheckBoxMenuItemDessinerRectanglePlein.setSelected(false);
            jCheckBoxMenuItemDessinerCercle.setSelected(false);
            jCheckBoxMenuItemDessinerCerclePlein.setSelected(true);
            observer.setMode(JLabelBeanCImage.SELECT_CERCLE_FILL);
        }
    }//GEN-LAST:event_jCheckBoxMenuItemDessinerCerclePleinActionPerformed

    private void jCheckBoxMenuItemDessinerCercleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItemDessinerCercleActionPerformed
        if (!jCheckBoxMenuItemDessinerCercle.isSelected()) observer.setMode(JLabelBeanCImage.INACTIF);
        else
        {
            jCheckBoxMenuItemDessinerPixel.setSelected(false);
            jCheckBoxMenuItemDessinerLigne.setSelected(false);
            jCheckBoxMenuItemDessinerRectangle.setSelected(false);
            jCheckBoxMenuItemDessinerRectanglePlein.setSelected(false);
            jCheckBoxMenuItemDessinerCercle.setSelected(true);
            jCheckBoxMenuItemDessinerCerclePlein.setSelected(false);
            observer.setMode(JLabelBeanCImage.SELECT_CERCLE);
        }
    }//GEN-LAST:event_jCheckBoxMenuItemDessinerCercleActionPerformed

    private void jMenuItemFourierAfficherPartieImaginaireActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFourierAfficherPartieImaginaireActionPerformed
        try 
        {
            int f_int[][] = imageNG.getMatrice();
            double f[][] = new double[imageNG.getLargeur()][imageNG.getHauteur()];
            for(int i=0 ; i<imageNG.getLargeur() ; i++)
                for(int j=0 ; j<imageNG.getHauteur() ; j++) f[i][j] = (double)(f_int[i][j]);
            
            System.out.println("Debut Fourier");
            MatriceComplexe fourier = Fourier.Fourier2D(f);
            System.out.println("Fin Fourier");
            fourier = Fourier.decroise(fourier);
            double partieImaginaire[][] = fourier.getPartieImaginaire();
            
            JDialogAfficheMatriceDouble dialog = new JDialogAfficheMatriceDouble(this,true,partieImaginaire,"Fourier : Affichage de la partie imaginaire");
            dialog.setVisible(true);
        } 
        catch (CImageNGException ex) 
        {
            System.out.println("Erreur CImageNG : " + ex.getMessage());
        }
    }//GEN-LAST:event_jMenuItemFourierAfficherPartieImaginaireActionPerformed

    private void jMenuItemFourierAfficherPartieReelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFourierAfficherPartieReelleActionPerformed
        try 
        {
            int f_int[][] = imageNG.getMatrice();
            double f[][] = new double[imageNG.getLargeur()][imageNG.getHauteur()];
            for(int i=0 ; i<imageNG.getLargeur() ; i++)
                for(int j=0 ; j<imageNG.getHauteur() ; j++) f[i][j] = (double)(f_int[i][j]);
            
            System.out.println("Debut Fourier");
            MatriceComplexe fourier = Fourier.Fourier2D(f);
            System.out.println("Fin Fourier");
            fourier = Fourier.decroise(fourier);
            double partieReelle[][] = fourier.getPartieReelle();
            
            JDialogAfficheMatriceDouble dialog = new JDialogAfficheMatriceDouble(this,true,partieReelle,"Fourier : Affichage de la partie reelle");
            dialog.setVisible(true);
        } 
        catch (CImageNGException ex) 
        {
            System.out.println("Erreur CImageNG : " + ex.getMessage());
        }

    }//GEN-LAST:event_jMenuItemFourierAfficherPartieReelleActionPerformed

    private void jMenuItemFourierAfficherPhaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFourierAfficherPhaseActionPerformed
        try 
        {
            int f_int[][] = imageNG.getMatrice();
            double f[][] = new double[imageNG.getLargeur()][imageNG.getHauteur()];
            for(int i=0 ; i<imageNG.getLargeur() ; i++)
                for(int j=0 ; j<imageNG.getHauteur() ; j++) f[i][j] = (double)(f_int[i][j]);
            
            System.out.println("Debut Fourier");
            MatriceComplexe fourier = Fourier.Fourier2D(f);
            System.out.println("Fin Fourier");
            fourier = Fourier.decroise(fourier);
            double phase[][] = fourier.getPhase();
            
            JDialogAfficheMatriceDouble dialog = new JDialogAfficheMatriceDouble(this,true,phase,"Fourier : Affichage de la phase");
            dialog.setVisible(true);
        } 
        catch (CImageNGException ex) 
        {
            System.out.println("Erreur CImageNG : " + ex.getMessage());
        }

    }//GEN-LAST:event_jMenuItemFourierAfficherPhaseActionPerformed

    private void jMenuItemFourierAfficherModuleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFourierAfficherModuleActionPerformed
        try 
        {
            int f_int[][] = imageNG.getMatrice();
            double f[][] = new double[imageNG.getLargeur()][imageNG.getHauteur()];
            for(int i=0 ; i<imageNG.getLargeur() ; i++)
                for(int j=0 ; j<imageNG.getHauteur() ; j++) f[i][j] = (double)(f_int[i][j]);
            
            System.out.println("Debut Fourier");
            MatriceComplexe fourier = Fourier.Fourier2D(f);
            System.out.println("Fin Fourier");
            fourier = Fourier.decroise(fourier);
            double module[][] = fourier.getModule();
            
            JDialogAfficheMatriceDouble dialog = new JDialogAfficheMatriceDouble(this,true,module,"Fourier : Affichage du module");
            dialog.setVisible(true);
        } 
        catch (CImageNGException ex) 
        {
            System.out.println("Erreur CImageNG : " + ex.getMessage());
        }
    }//GEN-LAST:event_jMenuItemFourierAfficherModuleActionPerformed

    private void jCheckBoxMenuItemDessinerPixelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItemDessinerPixelActionPerformed
        if (!jCheckBoxMenuItemDessinerPixel.isSelected()) observer.setMode(JLabelBeanCImage.INACTIF);
        else
        {
            jCheckBoxMenuItemDessinerPixel.setSelected(true);
            jCheckBoxMenuItemDessinerLigne.setSelected(false);
            jCheckBoxMenuItemDessinerRectangle.setSelected(false);
            jCheckBoxMenuItemDessinerRectanglePlein.setSelected(false);
            jCheckBoxMenuItemDessinerCercle.setSelected(false);
            jCheckBoxMenuItemDessinerCerclePlein.setSelected(false);
            observer.setMode(JLabelBeanCImage.CLIC);
        }
    }//GEN-LAST:event_jCheckBoxMenuItemDessinerPixelActionPerformed

    private void jMenuItemEnregistrerSousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEnregistrerSousActionPerformed
        JFileChooser choix = new JFileChooser();
	File fichier;
			
	choix.setCurrentDirectory(new File ("."));
	if (choix.showOpenDialog(null) == JFileChooser.APPROVE_OPTION)
	{
            fichier = choix.getSelectedFile();
            if (fichier != null)
            {
                try 
                {
                    if (resultImage != null) {
                        resultImage.enregistreFormatPNG(fichier);
                    } else if (imageRGB != null) {
                        imageRGB.enregistreFormatPNG(fichier);
                    } else if (imageNG != null) {
                        imageNG.enregistreFormatPNG(fichier);
                    }
                } 
                catch (IOException ex) 
                {
                    System.err.println("Erreur I/O : " + ex.getMessage());
                }
            }
	}
    }//GEN-LAST:event_jMenuItemEnregistrerSousActionPerformed

    
    
    private void jMenuItemOuvrirNGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemOuvrirNGActionPerformed
    JFileChooser choix = new JFileChooser();
    File fichier;

    choix.setCurrentDirectory(new File("."));
    if (choix.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
        fichier = choix.getSelectedFile();
        if (fichier != null) {
            try {
                imageNG = new CImageNG(fichier);

                int targetSlot = getSelectedSlotOrFirstEmpty();

                if (targetSlot != -1) {
                    setImageToSlot(targetSlot, imageNG);
                    clearAllSelections();
                } else {
                    JOptionPane.showMessageDialog(this, "Aucune case disponible !", "Erreur", JOptionPane.WARNING_MESSAGE);
                }

                imageRGB = null;
                activeMenusNG();
            } catch (IOException ex) {
                System.err.println("Erreur I/O : " + ex.getMessage());
            }
        }
    }

    }//GEN-LAST:event_jMenuItemOuvrirNGActionPerformed

    private void jMenuItemNouvelleNGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNouvelleNGActionPerformed
        JDialogNouvelleCImageNG dialog = new JDialogNouvelleCImageNG(this,true);
        dialog.setVisible(true);
        imageNG = dialog.getCImageNG();
        observer.setCImage(imageNG);
        imageRGB = null;
        activeMenusNG();
    }//GEN-LAST:event_jMenuItemNouvelleNGActionPerformed

    private void jMenuItemCouleurPinceauActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCouleurPinceauActionPerformed
        if (imageRGB != null)
        {
            Color newC = JColorChooser.showDialog(this,"Couleur du pinceau",couleurPinceauRGB);
            if (newC != null) couleurPinceauRGB = newC;
            observer.setCouleurPinceau(couleurPinceauRGB);
        }
        
        if (imageNG != null)
        {
            JDialogChoixCouleurNG dialog = new JDialogChoixCouleurNG(this,true,couleurPinceauNG);
            dialog.setVisible(true);
            couleurPinceauNG = dialog.getCouleur();
        }
    }//GEN-LAST:event_jMenuItemCouleurPinceauActionPerformed

    private void jCheckBoxMenuItemDessinerRectanglePleinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItemDessinerRectanglePleinActionPerformed
        if (!jCheckBoxMenuItemDessinerRectanglePlein.isSelected()) observer.setMode(JLabelBeanCImage.INACTIF);
        else
        {
            jCheckBoxMenuItemDessinerPixel.setSelected(false);
            jCheckBoxMenuItemDessinerLigne.setSelected(false);
            jCheckBoxMenuItemDessinerRectangle.setSelected(false);
            jCheckBoxMenuItemDessinerRectanglePlein.setSelected(true);
            jCheckBoxMenuItemDessinerCercle.setSelected(false);
            jCheckBoxMenuItemDessinerCerclePlein.setSelected(false);
            observer.setMode(JLabelBeanCImage.SELECT_RECT_FILL);
        }
    }//GEN-LAST:event_jCheckBoxMenuItemDessinerRectanglePleinActionPerformed

    private void jCheckBoxMenuItemDessinerRectangleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItemDessinerRectangleActionPerformed
        if (!jCheckBoxMenuItemDessinerRectangle.isSelected()) observer.setMode(JLabelBeanCImage.INACTIF);
        else
        {
            jCheckBoxMenuItemDessinerPixel.setSelected(false);
            jCheckBoxMenuItemDessinerLigne.setSelected(false);
            jCheckBoxMenuItemDessinerRectangle.setSelected(true);
            jCheckBoxMenuItemDessinerRectanglePlein.setSelected(false);
            jCheckBoxMenuItemDessinerCercle.setSelected(false);
            jCheckBoxMenuItemDessinerCerclePlein.setSelected(false);
            observer.setMode(JLabelBeanCImage.SELECT_RECT);
        }
    }//GEN-LAST:event_jCheckBoxMenuItemDessinerRectangleActionPerformed

    private void jCheckBoxMenuItemDessinerLigneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItemDessinerLigneActionPerformed
        if (!jCheckBoxMenuItemDessinerLigne.isSelected()) observer.setMode(JLabelBeanCImage.INACTIF);
        else
        {
            jCheckBoxMenuItemDessinerPixel.setSelected(false);
            jCheckBoxMenuItemDessinerLigne.setSelected(true);
            jCheckBoxMenuItemDessinerRectangle.setSelected(false);
            jCheckBoxMenuItemDessinerRectanglePlein.setSelected(false);
            jCheckBoxMenuItemDessinerCercle.setSelected(false);
            jCheckBoxMenuItemDessinerCerclePlein.setSelected(false);
            observer.setMode(JLabelBeanCImage.SELECT_LIGNE);
        }
    }//GEN-LAST:event_jCheckBoxMenuItemDessinerLigneActionPerformed

    private void jMenuItemNouvelleRGBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemNouvelleRGBActionPerformed
        JDialogNouvelleCImageRGB dialog = new JDialogNouvelleCImageRGB(this,true);
        dialog.setVisible(true);
        imageRGB = dialog.getCImageRGB();
        observer.setCImage(imageRGB);
        imageNG = null;
        activeMenusRGB();
    }//GEN-LAST:event_jMenuItemNouvelleRGBActionPerformed

    private void jMenuQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuQuitterActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuQuitterActionPerformed

    private void jMenuItemOuvrirRGBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemOuvrirRGBActionPerformed
    JFileChooser chooser = new JFileChooser();
    chooser.setCurrentDirectory(new File("."));
    if (chooser.showOpenDialog(null) == JFileChooser.APPROVE_OPTION) {
        File file = chooser.getSelectedFile();
        if (file != null) {
            try {
                imageRGB = new CImageRGB(file);
                int targetSlot = getSelectedSlot();
                if (targetSlot == -1) targetSlot = getFirstAvailableSlot();
                if (targetSlot != -1) {
                    setImageToSlot(targetSlot, imageRGB);
                    clearAllSelections();
                }
                observer.setCImage(imageRGB); // Keep existing functionality if observer is used
                imageNG = null;
                activeMenusRGB();
            } catch (IOException ex) {
                System.err.println("Erreur I/O : " + ex.getMessage());
            }
        }
    }
    }//GEN-LAST:event_jMenuItemOuvrirRGBActionPerformed

    private void jMenuItemFiltrageLineaireGlobalPasseBasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFiltrageLineaireGlobalPasseBasActionPerformed
        try {
            // Get the selected image from the grid
            CImage selected = getSelectedImage();
            if (selected == null || !(selected instanceof CImageNG)) {
                JOptionPane.showMessageDialog(this, "Veuillez sélectionner une image NG valide.");
                return;
            }

            CImageNG selectedNG = (CImageNG) selected;
            
            JDialogFiltrageLineaireGlobal dialog = new JDialogFiltrageLineaireGlobal(this, true, false);
            dialog.setVisible(true);
            
            if(!dialog.isFilled())
                return;
            
            int frequenceDeCoupure = dialog.getFrequenceDeCoupure();

            // Apply filter
            int[][] data = FiltrageLineaireGlobal.filtrePasseBasIdeal(selectedNG.getMatrice(), frequenceDeCoupure);
            data = Utils.normaliserImage(data, 0, 255);
            
            // Display result
            CImageNG updatedImage = new CImageNG(data);
            showResultImage(updatedImage);

        } catch (CImageNGException | HeadlessException e) {
            System.out.print("Erreur filtre passe-bas: " + e.getMessage());
        }
    }//GEN-LAST:event_jMenuItemFiltrageLineaireGlobalPasseBasActionPerformed

    private void jMenuItemFiltrageLineaireGlobalPasseHautActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFiltrageLineaireGlobalPasseHautActionPerformed
        try {
            // Get the selected image from the grid
            CImage selected = getSelectedImage();
            if (selected == null || !(selected instanceof CImageNG)) {
                JOptionPane.showMessageDialog(this, "Veuillez sélectionner une image NG valide.");
                return;
            }

            CImageNG selectedNG = (CImageNG) selected;
            
            JDialogFiltrageLineaireGlobal dialog = new JDialogFiltrageLineaireGlobal(this, true, false);
            dialog.setVisible(true);
            
            if(!dialog.isFilled())
                return;
            
            int frequenceDeCoupure = dialog.getFrequenceDeCoupure();
            
            // Apply filter
            int[][] data = FiltrageLineaireGlobal.filtrePasseHautIdeal(selectedNG.getMatrice(), frequenceDeCoupure);
            data = Utils.normaliserImage(data, 0, 255);

            // Display result
            CImageNG updatedImage = new CImageNG(data);
            showResultImage(updatedImage);
            
        }catch (CImageNGException | HeadlessException e){
            System.out.print("Erreur filtre passe-haut: " + e.getMessage());
        }
    }//GEN-LAST:event_jMenuItemFiltrageLineaireGlobalPasseHautActionPerformed

    private void jMenuItemFiltrageLineaireGlobalPasseBasButterworthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFiltrageLineaireGlobalPasseBasButterworthActionPerformed
        try {
            // Get the selected image from the grid
            CImage selected = getSelectedImage();
            if (selected == null || !(selected instanceof CImageNG)) {
                JOptionPane.showMessageDialog(this, "Veuillez sélectionner une image NG valide.");
                return;
            }

            CImageNG selectedNG = (CImageNG) selected;
            
            JDialogFiltrageLineaireGlobal dialog = new JDialogFiltrageLineaireGlobal(this, true, true);
            dialog.setVisible(true);
            
            if(!dialog.isFilled())
                return;
            
            int frequenceDeCoupure = dialog.getFrequenceDeCoupure();
            int ordre = dialog.getOrdre();
            
            // Apply filter
            int[][] data = FiltrageLineaireGlobal.filtrePasseHautButterworth(selectedNG.getMatrice(), frequenceDeCoupure, ordre);
            data = Utils.normaliserImage(data, 0, 255);

            // Display result
            CImageNG updatedImage = new CImageNG(data);
            showResultImage(updatedImage);
            
        }catch (CImageNGException | HeadlessException e){
            System.out.print("Erreur filtre passe-haut butterworth: " + e.getMessage());
        }
    }//GEN-LAST:event_jMenuItemFiltrageLineaireGlobalPasseBasButterworthActionPerformed

    private void jMenuItemFiltrageLineaireGlobalPasseHautButterworthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFiltrageLineaireGlobalPasseHautButterworthActionPerformed
        try {
            // Get the selected image from the grid
            CImage selected = getSelectedImage();
            if (selected == null || !(selected instanceof CImageNG)) {
                JOptionPane.showMessageDialog(this, "Veuillez sélectionner une image NG valide.");
                return;
            }

            CImageNG selectedNG = (CImageNG) selected;
            
            JDialogFiltrageLineaireGlobal dialog = new JDialogFiltrageLineaireGlobal(this, true, true);
            dialog.setVisible(true);
            
            if(!dialog.isFilled())
                return;
            
            int frequenceDeCoupure = dialog.getFrequenceDeCoupure();
            int ordre = dialog.getOrdre();
            
            // Apply filter
            int[][] data = FiltrageLineaireGlobal.filtrePasseBasButterworth(selectedNG.getMatrice(), frequenceDeCoupure, ordre);
            data = Utils.normaliserImage(data, 0, 255);

            // Display result
            CImageNG updatedImage = new CImageNG(data);
            showResultImage(updatedImage);
            
        }catch (CImageNGException | HeadlessException e){
            System.out.print("Erreur filtre passe-bas butterworth: " + e.getMessage());
        }
    }//GEN-LAST:event_jMenuItemFiltrageLineaireGlobalPasseHautButterworthActionPerformed

    private void jMenuItemFiltrageLineaireLocalFiltrageConvolutionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFiltrageLineaireLocalFiltrageConvolutionActionPerformed
        try {
            // Get the selected image from the grid
            CImage selected = getSelectedImage();
            if (selected == null || !(selected instanceof CImageNG)) {
                JOptionPane.showMessageDialog(this, "Veuillez sélectionner une image NG valide.");
                return;
            }

            CImageNG selectedNG = (CImageNG) selected;
            
            JDialogFiltrageLineaireLocal choixMasque = new JDialogFiltrageLineaireLocal(this, true, false);
            choixMasque.setVisible(true);
            
            if(!choixMasque.isFilled())
                return;
            
            double[][] masque = choixMasque.getMasque();
            
            int[][] data = FiltrageLineaireLocal.filtreMasqueConvolution(selectedNG.getMatrice(), masque);
            data = Utils.normaliserImage(data, 0, 255);

            // Display result
            CImageNG updatedImage = new CImageNG(data);
            showResultImage(updatedImage);
            
        }catch (CImageNGException | HeadlessException e){
            System.out.print("Erreur filtre convolution: " + e.getMessage());
        }
    }//GEN-LAST:event_jMenuItemFiltrageLineaireLocalFiltrageConvolutionActionPerformed

    private void jMenuItemFiltrageLineaireLocalFiltrageMoyenneurActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemFiltrageLineaireLocalFiltrageMoyenneurActionPerformed
        try {
            // Get the selected image from the grid
            CImage selected = getSelectedImage();
            if (selected == null || !(selected instanceof CImageNG)) {
                JOptionPane.showMessageDialog(this, "Veuillez sélectionner une image NG valide.");
                return;
            }

            CImageNG selectedNG = (CImageNG) selected;
            
            JDialogFiltrageLineaireLocal choixMasque = new JDialogFiltrageLineaireLocal(this, true, true);
            choixMasque.setVisible(true);
            
            if(!choixMasque.isFilled())
                return;
            
            int tailleMasque = choixMasque.getTailleMasque();
           
            int[][] data = FiltrageLineaireLocal.filtreMoyenneur(selectedNG.getMatrice(), tailleMasque);
            data = Utils.normaliserImage(data, 0, 255);

            // Display result
            CImageNG updatedImage = new CImageNG(data);
            showResultImage(updatedImage);
            
        }catch (CImageNGException | HeadlessException e){
            System.out.print("Erreur filtre moyenneur: " + e.getMessage());
        }
    }//GEN-LAST:event_jMenuItemFiltrageLineaireLocalFiltrageMoyenneurActionPerformed

    private void jMenuItemTraitementLineaireMorphologieElementaireErosionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTraitementLineaireMorphologieElementaireErosionActionPerformed
        try{
            // Get the selected image from the grid
            CImage selected = getSelectedImage();
            if (selected == null || !(selected instanceof CImageNG)) {
                JOptionPane.showMessageDialog(this, "Veuillez sélectionner une image NG valide.");
                return;
            }

            CImageNG selectedNG = (CImageNG) selected;
            int[][] image = selectedNG.getMatrice();
            
            if(Utils.estImageBinaire(image)){
                image = Utils.convertirBinaireVersNiveauxDeGris(image);
            }
            
            JDialogMorpho morpho = new JDialogMorpho(this, true, true);
            morpho.setVisible(true);
            
            if(!morpho.isFilled())
                return;
            
            int tailleMasque = morpho.getTailleMasque();
            
            int[][] data = MorphoElementaire.erosion(image, tailleMasque);
            data = Utils.normaliserImage(data, 0, 255);

            // Display result
            CImageNG updatedImage = new CImageNG(data);
            showResultImage(updatedImage);            
            
        }catch (CImageNGException | HeadlessException e){
            System.out.print("Erreur morphologie elementaire erosion: " + e.getMessage());
        }
    }//GEN-LAST:event_jMenuItemTraitementLineaireMorphologieElementaireErosionActionPerformed

    private void jMenuItemTraitementLineaireMorphologieElementaireDilatationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTraitementLineaireMorphologieElementaireDilatationActionPerformed
        try{
            // Get the selected image from the grid
            CImage selected = getSelectedImage();
            if (selected == null || !(selected instanceof CImageNG)) {
                JOptionPane.showMessageDialog(this, "Veuillez sélectionner une image NG valide.");
                return;
            }

            CImageNG selectedNG = (CImageNG) selected;
            int[][] image = selectedNG.getMatrice();
            
            if(Utils.estImageBinaire(image)){
                image = Utils.convertirBinaireVersNiveauxDeGris(image);
            }
            
            JDialogMorpho morpho = new JDialogMorpho(this, true, true);
            morpho.setVisible(true);
            
            if(!morpho.isFilled())
                return;
            
            int tailleMasque = morpho.getTailleMasque();
            
            int[][] data = MorphoElementaire.dilatation(image, tailleMasque);
            data = Utils.normaliserImage(data, 0, 255);

            // Display result
            CImageNG updatedImage = new CImageNG(data);
            showResultImage(updatedImage);
                        
        }catch (CImageNGException | HeadlessException e){
            System.out.print("Erreur morphologie elementaire dilatation: " + e.getMessage());
        }
    }//GEN-LAST:event_jMenuItemTraitementLineaireMorphologieElementaireDilatationActionPerformed

    private void jMenuItemTraitementLineaireMorphologieElementaireOuvertureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTraitementLineaireMorphologieElementaireOuvertureActionPerformed
        try{
            // Get the selected image from the grid
            CImage selected = getSelectedImage();
            if (selected == null || !(selected instanceof CImageNG)) {
                JOptionPane.showMessageDialog(this, "Veuillez sélectionner une image NG valide.");
                return;
            }

            CImageNG selectedNG = (CImageNG) selected;
            int[][] image = selectedNG.getMatrice();
            
            if(Utils.estImageBinaire(image)){
                image = Utils.convertirBinaireVersNiveauxDeGris(image);
            }
            
            JDialogMorpho morpho = new JDialogMorpho(this, true, true);
            morpho.setVisible(true);
            
            if(!morpho.isFilled())
                return;
            
            int tailleMasque = morpho.getTailleMasque();
            
            int[][] data = MorphoElementaire.ouverture(image, tailleMasque);
            data = Utils.normaliserImage(data, 0, 255);

            // Display result
            CImageNG updatedImage = new CImageNG(data);
            showResultImage(updatedImage);
            
        }catch (CImageNGException | HeadlessException e){
            System.out.print("Erreur morphologie elementaire ouverture: " + e.getMessage());
        }
    }//GEN-LAST:event_jMenuItemTraitementLineaireMorphologieElementaireOuvertureActionPerformed

    private void jMenuItemTraitementLineaireMorphologieElementaireFermetureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTraitementLineaireMorphologieElementaireFermetureActionPerformed
        try{
            // Get the selected image from the grid
            CImage selected = getSelectedImage();
            if (selected == null || !(selected instanceof CImageNG)) {
                JOptionPane.showMessageDialog(this, "Veuillez sélectionner une image NG valide.");
                return;
            }

            CImageNG selectedNG = (CImageNG) selected;
            int[][] image = selectedNG.getMatrice();
            
            if(Utils.estImageBinaire(image)){
                image = Utils.convertirBinaireVersNiveauxDeGris(image);
            }
            
            JDialogMorpho morpho = new JDialogMorpho(this, true, true);
            morpho.setVisible(true);
            
            if(!morpho.isFilled())
                return;
            
            int tailleMasque = morpho.getTailleMasque();
            
            int[][] data = MorphoElementaire.fermeture(image, tailleMasque);
            data = Utils.normaliserImage(data, 0, 255);

            // Display result
            CImageNG updatedImage = new CImageNG(data);
            showResultImage(updatedImage);
            
        }catch (CImageNGException | HeadlessException e){
            System.out.print("Erreur morphologie elementaire fermeture: " + e.getMessage());
        }
    }//GEN-LAST:event_jMenuItemTraitementLineaireMorphologieElementaireFermetureActionPerformed

    private void jMenuItemTraitementLineaireMorphologieComplexeDilatationGeodesiqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTraitementLineaireMorphologieComplexeDilatationGeodesiqueActionPerformed
    try {
        CImage[] selectedImages = getAllSelectedImages();

        if (selectedImages == null || selectedImages.length != 2) {
            JOptionPane.showMessageDialog(this, "Veuillez sélectionner exactement deux images NG.");
            return;
        }

        for (int i = 0; i < selectedImages.length; i++) {
            if (!(selectedImages[i] instanceof CImageNG)) {
                JOptionPane.showMessageDialog(this, "Les deux images doivent être de type NG.");
                return;
            }
        }

        // Extract images
        CImageNG imgInit = (CImageNG) selectedImages[0]; // Image à dilater
        CImageNG imgMasque = (CImageNG) selectedImages[1]; // Masque géodésique

        int[][] image = imgInit.getMatrice();
        int[][] masqueGeodesique = imgMasque.getMatrice();
        
        JDialogMorpho morpho = new JDialogMorpho(this, true, true);
        morpho.setVisible(true);
            
        if(!morpho.isFilled())
            return;
            
        int nbIter = morpho.getIter();

        int[][] data = MorphoComplexe.dilatationGeodesique(image, masqueGeodesique, nbIter);
        data = Utils.normaliserImage(data, 0, 255);

        // Display result
        CImageNG updatedImage = new CImageNG(data);
        showResultImage(updatedImage);

    } catch (CImageNGException | HeadlessException e) {
        System.out.println("Erreur Dilatation Géodésique: " + e.getMessage());
    }
        
    }//GEN-LAST:event_jMenuItemTraitementLineaireMorphologieComplexeDilatationGeodesiqueActionPerformed

    private void jMenuItemTraitementLineaireMorphologieComplexeReconstructionGeodesiqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTraitementLineaireMorphologieComplexeReconstructionGeodesiqueActionPerformed
        try {
            CImage[] selectedImages = getAllSelectedImages();

            if (selectedImages == null || selectedImages.length != 2) {
                JOptionPane.showMessageDialog(this, "Veuillez sélectionner exactement deux images NG.");
                return;
            }

            for (int i = 0; i < selectedImages.length; i++) {
                if (!(selectedImages[i] instanceof CImageNG)) {
                    JOptionPane.showMessageDialog(this, "Les deux images doivent être de type NG.");
                    return;
                }
            }

            // Extract images
            CImageNG imgInit = (CImageNG) selectedImages[0]; // Image à dilater
            CImageNG imgMasque = (CImageNG) selectedImages[1]; // Masque géodésique

            int[][] image = imgInit.getMatrice();
            int[][] masqueGeodesique = imgMasque.getMatrice();

            int[][] data = MorphoComplexe.reconstructionGeodesique(image, masqueGeodesique);
            data = Utils.normaliserImage(data, 0, 255);

            // Display result
            CImageNG updatedImage = new CImageNG(data);
            showResultImage(updatedImage);

        } catch (CImageNGException | HeadlessException e) {
            System.out.println("Erreur Dilatation Géodésique: " + e.getMessage());
        }
            
    }//GEN-LAST:event_jMenuItemTraitementLineaireMorphologieComplexeReconstructionGeodesiqueActionPerformed
    
    private void jMenuTraitementComplexeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuTraitementComplexeActionPerformed
        //
    }//GEN-LAST:event_jMenuTraitementComplexeActionPerformed

    private void jMenuItemTraitementLineaireMorphologieComplexeFiltreMedianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemTraitementLineaireMorphologieComplexeFiltreMedianActionPerformed
        try {
            CImage selectedImage = getSelectedImage();


            if (!(selectedImage instanceof CImageNG)) {
                JOptionPane.showMessageDialog(this, "L'images doit être de type NG.");
                return;
            }

            // Change selectedImage -> CImageNG
            CImageNG selectedImageNG = (CImageNG) selectedImage;
            int[][] image = selectedImageNG.getMatrice();

            JDialogMorpho morpho = new JDialogMorpho(this, true, true);
            morpho.setVisible(true);

            if(!morpho.isFilled())
                return;

            int tailleMasque = morpho.getTailleMasque();

            int[][] data = MorphoComplexe.filtreMedian(image, tailleMasque);
            data = Utils.normaliserImage(data, 0, 255);

            // Display result
            CImageNG updatedImage = new CImageNG(data);
            showResultImage(updatedImage);

        } catch (CImageNGException | HeadlessException e) {
          System.out.println("Erreur Dilatation Géodésique: " + e.getMessage());
        }
    }//GEN-LAST:event_jMenuItemTraitementLineaireMorphologieComplexeFiltreMedianActionPerformed

    private void jMenuAfficherParametresImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuAfficherParametresImageActionPerformed
        try {
            CImage selectedImage = getSelectedImage();

            if (!(selectedImage instanceof CImageNG)) {
                JOptionPane.showMessageDialog(this, "L'images doit être de type NG.");
                return;
            }

            // Change selectedImage -> CImageNG
            CImageNG selectedImageNG = (CImageNG) selectedImage;
            int[][] image = selectedImageNG.getMatrice();

            int min = Histogramme.minimum(image);
            int max = Histogramme.maximum(image);
            int lum = Histogramme.luminance(image);
            
            double contraste1 = Histogramme.contraste1(image);
            double contraste2 = Histogramme.contraste2(image);
            
            JDialogAfficheInformationImage dialog = new JDialogAfficheInformationImage(this, true, min, max, lum, contraste1, contraste2);
            dialog.setVisible(true);

        } catch (CImageNGException | HeadlessException e) {
            System.out.println("Erreur Dilatation Géodésique: " + e.getMessage());
        }
    }//GEN-LAST:event_jMenuAfficherParametresImageActionPerformed

    private void jMenuItemContoursLineairePrewittActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemContoursLineairePrewittActionPerformed
        try {
            // Get the selected image from the grid
            CImage selected = getSelectedImage();
            if (selected == null || !(selected instanceof CImageNG)) {
                JOptionPane.showMessageDialog(this, "Veuillez sélectionner une image NG valide.");
                return;
            }

            CImageNG selectedNG = (CImageNG) selected;
            
            JDialogContoursLineaire dialog = new JDialogContoursLineaire(this, true);
            dialog.setVisible(true);
            
            if(!dialog.isFilled())
                return;
            
            int dir = dialog.getDir();

            // Apply filter
            int[][] data = ContoursLineaire.gradientPrewitt(selectedNG.getMatrice(), dir);
            data = Utils.normaliserImage(data, 0, 255);
            
            // Display result
            CImageNG updatedImage = new CImageNG(data);
            showResultImage(updatedImage);

        } catch (CImageNGException | HeadlessException e) {
            System.out.print("Erreur Gradient Prewitt: " + e.getMessage());
        }
    }//GEN-LAST:event_jMenuItemContoursLineairePrewittActionPerformed

    private void jMenuItemContoursLineaireSobelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemContoursLineaireSobelActionPerformed
        try {
            // Get the selected image from the grid
            CImage selected = getSelectedImage();
            if (selected == null || !(selected instanceof CImageNG)) {
                JOptionPane.showMessageDialog(this, "Veuillez sélectionner une image NG valide.");
                return;
            }

            CImageNG selectedNG = (CImageNG) selected;
            
            JDialogContoursLineaire dialog = new JDialogContoursLineaire(this, true);
            dialog.setVisible(true);
            
            if(!dialog.isFilled())
                return;
            
            int dir = dialog.getDir();

            // Apply filter
            int[][] data = ContoursLineaire.gradientSobel(selectedNG.getMatrice(), dir);
            data = Utils.normaliserImage(data, 0, 255);
            
            // Display result
            CImageNG updatedImage = new CImageNG(data);
            showResultImage(updatedImage);

        } catch (CImageNGException | HeadlessException e) {
            System.out.print("Erreur Gradient Sobel: " + e.getMessage());
        }
    }//GEN-LAST:event_jMenuItemContoursLineaireSobelActionPerformed

    private void jMenuItemContoursLineaireLaplacien4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemContoursLineaireLaplacien4ActionPerformed
        try {
            // Get the selected image from the grid
            CImage selected = getSelectedImage();
            if (selected == null || !(selected instanceof CImageNG)) {
                JOptionPane.showMessageDialog(this, "Veuillez sélectionner une image NG valide.");
                return;
            }

            CImageNG selectedNG = (CImageNG) selected;

            // Apply filter
            int[][] data = ContoursLineaire.laplacien4(selectedNG.getMatrice());
            data = Utils.normaliserImage(data, 0, 255);
            
            // Display result
            CImageNG updatedImage = new CImageNG(data);
            showResultImage(updatedImage);

        } catch (CImageNGException | HeadlessException e) {
            System.out.print("Erreur Laplacien 4: " + e.getMessage());
        }
    }//GEN-LAST:event_jMenuItemContoursLineaireLaplacien4ActionPerformed

    private void jMenuItemContoursLineaireLaplacien8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemContoursLineaireLaplacien8ActionPerformed
        try {
            // Get the selected image from the grid
            CImage selected = getSelectedImage();
            if (selected == null || !(selected instanceof CImageNG)) {
                JOptionPane.showMessageDialog(this, "Veuillez sélectionner une image NG valide.");
                return;
            }

            CImageNG selectedNG = (CImageNG) selected;

            // Apply filter
            int[][] data = ContoursLineaire.laplacien8(selectedNG.getMatrice());
            data = Utils.normaliserImage(data, 0, 255);
            
            // Display result
            CImageNG updatedImage = new CImageNG(data);
            showResultImage(updatedImage);

        } catch (CImageNGException | HeadlessException e) {
            System.out.print("Erreur Laplacien 8: " + e.getMessage());
        }
    }//GEN-LAST:event_jMenuItemContoursLineaireLaplacien8ActionPerformed

    private void jMenuItemContoursNonLineaireErosionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemContoursNonLineaireErosionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemContoursNonLineaireErosionActionPerformed

    private void jMenuItemContoursNonLineaireLaplacienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemContoursNonLineaireLaplacienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemContoursNonLineaireLaplacienActionPerformed

    private void jMenuItemContoursNonLineaireDilatationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemContoursNonLineaireDilatationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemContoursNonLineaireDilatationActionPerformed

    private void jMenuItemContoursNonLineaireBeucherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemContoursNonLineaireBeucherActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemContoursNonLineaireBeucherActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            new IsilImageProcessing().setVisible(true);
        });
    }

    @Override
    public void ClicDetected(UnClicEvent e) 
    {
        if (jCheckBoxMenuItemDessinerPixel.isSelected())
        {   
            try 
            {
                if (imageRGB != null) 
                    imageRGB.setPixel(e.getX(),e.getY(),couleurPinceauRGB);
                if (imageNG != null) 
                    imageNG.setPixel(e.getX(),e.getY(),couleurPinceauNG);
            } 
            catch (CImageRGBException ex) 
            { System.out.println("Erreur RGB : " + ex.getMessage()); }
            catch (CImageNGException ex) 
            { System.out.println("Erreur NG : " + ex.getMessage()); }
        }
    }

    @Override
    public void SelectLigneDetected(DeuxClicsEvent e) 
    {
        if (jCheckBoxMenuItemDessinerLigne.isSelected())
        {   
            try 
            {
                if (imageRGB != null) 
                    imageRGB.DessineLigne(e.getX1(),e.getY1(),e.getX2(),e.getY2(),couleurPinceauRGB);
                if (imageNG != null) 
                    imageNG.DessineLigne(e.getX1(),e.getY1(),e.getX2(),e.getY2(),couleurPinceauNG);
            } 
            catch (CImageRGBException ex) 
            { System.out.println("Erreur RGB : " + ex.getMessage()); }
            catch (CImageNGException ex) 
            { System.out.println("Erreur NG : " + ex.getMessage()); }
        }
    }

    @Override
    public void SelectRectDetected(DeuxClicsEvent e) 
    {
        if (jCheckBoxMenuItemDessinerRectangle.isSelected())
        {   
            try 
            {
                if (imageRGB != null)
                    imageRGB.DessineRect(e.getX1(),e.getY1(),e.getX2(),e.getY2(),couleurPinceauRGB);
                if (imageNG != null)
                    imageNG.DessineRect(e.getX1(),e.getY1(),e.getX2(),e.getY2(),couleurPinceauNG);
            } 
            catch (CImageRGBException ex) 
            { System.out.println("Erreur RGB : " + ex.getMessage()); }
            catch (CImageNGException ex) 
            { System.out.println("Erreur NG : " + ex.getMessage()); }
        }
    }

    @Override
    public void SelectCercleDetected(DeuxClicsEvent e) 
    {
        if (jCheckBoxMenuItemDessinerCercle.isSelected())
        {   
            try 
            {
                if (imageRGB != null)
                    imageRGB.DessineCercle(e.getX1(),e.getY1(),e.getX2(),e.getY2(),couleurPinceauRGB);
                if (imageNG != null)
                    imageNG.DessineCercle(e.getX1(),e.getY1(),e.getX2(),e.getY2(),couleurPinceauNG);
            } 
            catch (CImageRGBException ex) 
            { System.out.println("Erreur RGB : " + ex.getMessage()); }
            catch (CImageNGException ex) 
            { System.out.println("Erreur NG : " + ex.getMessage()); }
        }
    }

    @Override
    public void SelectCercleFillDetected(DeuxClicsEvent e) 
    {
        if (jCheckBoxMenuItemDessinerCerclePlein.isSelected())
        {   
            try 
            {
                if (imageRGB != null)
                    imageRGB.RemplitCercle(e.getX1(),e.getY1(),e.getX2(),e.getY2(),couleurPinceauRGB);
                if (imageNG != null)
                    imageNG.RemplitCercle(e.getX1(),e.getY1(),e.getX2(),e.getY2(),couleurPinceauNG);
            } 
            catch (CImageRGBException ex) 
            { System.out.println("Erreur RGB : " + ex.getMessage()); }
            catch (CImageNGException ex) 
            { System.out.println("Erreur NG : " + ex.getMessage()); }
        }
    }

    @Override
    public void SelectRectFillDetected(DeuxClicsEvent e) 
    {
        if (jCheckBoxMenuItemDessinerRectanglePlein.isSelected())
        {   
            try 
            {
                if (imageRGB != null) 
                    imageRGB.RemplitRect(e.getX1(),e.getY1(),e.getX2(),e.getY2(),couleurPinceauRGB);
                if (imageNG != null) 
                    imageNG.RemplitRect(e.getX1(),e.getY1(),e.getX2(),e.getY2(),couleurPinceauNG);
            } 
            catch (CImageRGBException ex) 
            { System.out.println("Erreur RGB : " + ex.getMessage()); }
            catch (CImageNGException ex) 
            { System.out.println("Erreur NG : " + ex.getMessage()); }
        }
    }
    
    // ANTOINE WAS HERE
    private void setupImageGridSlots() {
        panelGrid.removeAll();

        panelGrid.setLayout(new GridLayout(3, 3, 5, 5)); // 3x3 grid with spacing

        for (int i = 0; i < 9; i++) {
            final int index = i;

            JLabel slot = new JLabel("Slot " + (i + 1), SwingConstants.CENTER);
            slot.setPreferredSize(new Dimension(150, 150));
            slot.setOpaque(true);
            slot.setBackground(Color.WHITE);
            slot.setBorder(BorderFactory.createLineBorder(Color.BLACK));

            // Click to select/deselect
            slot.addMouseListener(new java.awt.event.MouseAdapter() {
                @Override
                public void mouseClicked(java.awt.event.MouseEvent evt) {
                    if (currentGridMode == GridMode.MOVE) {
                        if (liftedImage == null && imagesInSlots[index] != null) {
                            // LIFT
                            clearAllSelections();

                            liftedImage = imagesInSlots[index];
                            liftedFromIndex = index;
                            imageSlots[index].setBorder(BorderFactory.createLineBorder(Color.ORANGE, 3));


                        } else if (liftedImage != null) {
                            // DROP
                            clearAllSelections();
                            if (liftedFromIndex >= 0) {
                                // Swap images
                                CImage temp = imagesInSlots[index];
                                setImageToSlot(index, liftedImage);
                                setImageToSlot(liftedFromIndex, temp);

                            } else if (liftedFromIndex == -1) {
                                // Move from result to grid
                                setImageToSlot(index, liftedImage);
                                resultPanel.setIcon(null);
                                resultImage = null;
                                resultPanel.setBorder(BorderFactory.createLineBorder(Color.BLACK, 1));
                            }


                            liftedImage = null;
                            liftedFromIndex = -2;

                            clearAllSelections(); // also clear after drop
                        }

                    } else if (currentGridMode == GridMode.SELECT) {
                        // Toggle selection
                        selectedSlots[index] = !selectedSlots[index];
                        if (selectedSlots[index]) {
                            slot.setBorder(BorderFactory.createLineBorder(Color.YELLOW, 4));
                        } else {
                            slot.setBorder(BorderFactory.createLineBorder(Color.BLACK, 1));
                        }
                    }
                }
            });


            imageSlots[i] = slot;
            panelGrid.add(slot);
        }

        panelGrid.revalidate();
        panelGrid.repaint();
    }

    private void setImageToSlot(int index, CImage image) {
        if (index < 0 || index >= 9 || image == null) return;

        imagesInSlots[index] = image;

        Image raw = image.getImage();
        Image scaled = raw.getScaledInstance(imageSlots[index].getWidth(), imageSlots[index].getHeight(), Image.SCALE_SMOOTH);
        imageSlots[index].setIcon(new ImageIcon(scaled));
        imageSlots[index].setText(""); // Clear label text

        selectedSlots[index] = false;
        imageSlots[index].setBorder(BorderFactory.createLineBorder(Color.BLACK, 1));
    }


    private int getSelectedSlotOrFirstEmpty() {
        for (int i = 0; i < selectedSlots.length; i++) {
            if (selectedSlots[i]) {
                return i; // Use first selected slot
            }
        }

        // If no selection, find first empty
        for (int i = 0; i < imagesInSlots.length; i++) {
            if (imagesInSlots[i] == null) {
                return i;
            }
        }

        return -1; // No slot available
    }
    
    private void clearAllSelections() {
        for (int i = 0; i < selectedSlots.length; i++) {
            selectedSlots[i] = false;
            imageSlots[i].setBackground(Color.WHITE);
            imageSlots[i].setBorder(BorderFactory.createLineBorder(Color.BLACK, 1)); // 🟡 reset border too
        }

        resultPanel.setBorder(BorderFactory.createLineBorder(Color.BLACK, 1));
    }


    private int getSelectedSlot() {
        for (int i = 0; i < selectedSlots.length; i++) {
            if (selectedSlots[i]) return i;
        }
        return -1;
    }
    
    private CImage[] getAllSelectedImages() {
        int count = 0;
        for (int i = 0; i < selectedSlots.length; i++) {
            if (selectedSlots[i] && imagesInSlots[i] != null) {
                count++;
            }
        }

        if (count == 0) {
            return null; // No valid image selected
        }

        CImage[] selectedImages = new CImage[count];
        int index = 0;

        for (int i = 0; i < selectedSlots.length; i++) {
            if (selectedSlots[i] && imagesInSlots[i] != null) {
                selectedImages[index++] = imagesInSlots[i];
            }
        }

        return selectedImages;
    }
    


    private int getFirstAvailableSlot() {
        for (int i = 0; i < imagesInSlots.length; i++) {
            if (imagesInSlots[i] == null) return i;
        }
        return -1;
    }

    private CImage getSelectedImage() {
        for (int i = 0; i < selectedSlots.length; i++) {
            if (selectedSlots[i] && imagesInSlots[i] != null) {
                return imagesInSlots[i];
            }
        }
        return null;
    }


        // Add a button and a keybind (default is m) to swap between move and select mode
    private void setupModeToggleUI() {
            toolBar = new JToolBar();
            JToggleButton toggleButton = new JToggleButton("Mode Déplacement");
            toggleButton.setFocusable(false);

            currentGridMode = GridMode.SELECT;

            toggleButton.addActionListener(e -> {
                currentGridMode = toggleButton.isSelected() ? GridMode.MOVE : GridMode.SELECT;
                clearAllSelections();
            });

            toolBar.add(toggleButton);
            getContentPane().add(toolBar, BorderLayout.NORTH);

            KeyStroke keyStroke = KeyStroke.getKeyStroke("M");
            panelGrid.getInputMap(JComponent.WHEN_IN_FOCUSED_WINDOW).put(keyStroke, "toggleMode");
            panelGrid.getActionMap().put("toggleMode", new AbstractAction() {
                @Override
                public void actionPerformed(ActionEvent e) {
                    clearAllSelections();
                    toggleButton.setSelected(!toggleButton.isSelected());
                    currentGridMode = toggleButton.isSelected() ? GridMode.MOVE : GridMode.SELECT;
                }
            });
            
            // Add the input field button
            setupValueUI();
        }


     // Add an Input field at the top between MIN & MAX, the value can be called with Integer.parseInt(inputField.getText())
    void setupValueUI() {

        // Create the input field
        inputField = new JTextField(5);
        inputField.setMaximumSize(new Dimension(50, 25));

        toolBar.add(new JLabel(" Valeur : "));
        toolBar.add(inputField);
    }

    
    // MY Variable declaration - Antoine
    private boolean[] selectedSlots = new boolean[9];
    private CImage[] imagesInSlots = new CImage[9];
    private JLabel[] imageSlots = new JLabel[9];
    private JToolBar toolBar;

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroupDessiner;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItemDessinerCercle;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItemDessinerCerclePlein;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItemDessinerLigne;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItemDessinerPixel;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItemDessinerRectangle;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItemDessinerRectanglePlein;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuItem jMenuAfficherParametresImage;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuContours;
    private javax.swing.JMenu jMenuContoursLineaire;
    private javax.swing.JMenu jMenuContoursNonLineaire;
    private javax.swing.JMenu jMenuDessiner;
    private javax.swing.JMenu jMenuFourier;
    private javax.swing.JMenu jMenuFourierAfficher;
    private javax.swing.JMenu jMenuHistogramme;
    private javax.swing.JMenuItem jMenuHistogrammeAfficher;
    private javax.swing.JMenu jMenuImage;
    private javax.swing.JMenuItem jMenuItemContoursLineaireLaplacien4;
    private javax.swing.JMenuItem jMenuItemContoursLineaireLaplacien8;
    private javax.swing.JMenuItem jMenuItemContoursLineairePrewitt;
    private javax.swing.JMenuItem jMenuItemContoursLineaireSobel;
    private javax.swing.JMenuItem jMenuItemContoursNonLineaireBeucher;
    private javax.swing.JMenuItem jMenuItemContoursNonLineaireDilatation;
    private javax.swing.JMenuItem jMenuItemContoursNonLineaireErosion;
    private javax.swing.JMenuItem jMenuItemContoursNonLineaireLaplacien;
    private javax.swing.JMenuItem jMenuItemCouleurPinceau;
    private javax.swing.JMenuItem jMenuItemEnregistrerSous;
    private javax.swing.JMenuItem jMenuItemFiltrageLineaireGlobalPasseBas;
    private javax.swing.JMenuItem jMenuItemFiltrageLineaireGlobalPasseBasButterworth;
    private javax.swing.JMenuItem jMenuItemFiltrageLineaireGlobalPasseHaut;
    private javax.swing.JMenuItem jMenuItemFiltrageLineaireGlobalPasseHautButterworth;
    private javax.swing.JMenuItem jMenuItemFiltrageLineaireLocalFiltrageConvolution;
    private javax.swing.JMenuItem jMenuItemFiltrageLineaireLocalFiltrageMoyenneur;
    private javax.swing.JMenuItem jMenuItemFourierAfficherModule;
    private javax.swing.JMenuItem jMenuItemFourierAfficherPartieImaginaire;
    private javax.swing.JMenuItem jMenuItemFourierAfficherPartieReelle;
    private javax.swing.JMenuItem jMenuItemFourierAfficherPhase;
    private javax.swing.JMenuItem jMenuItemNouvelleNG;
    private javax.swing.JMenuItem jMenuItemNouvelleRGB;
    private javax.swing.JMenuItem jMenuItemOuvrirNG;
    private javax.swing.JMenuItem jMenuItemOuvrirRGB;
    private javax.swing.JMenuItem jMenuItemTraitementLineaireMorphologieComplexeDilatationGeodesique;
    private javax.swing.JMenuItem jMenuItemTraitementLineaireMorphologieComplexeFiltreMedian;
    private javax.swing.JMenuItem jMenuItemTraitementLineaireMorphologieComplexeReconstructionGeodesique;
    private javax.swing.JMenuItem jMenuItemTraitementLineaireMorphologieElementaireDilatation;
    private javax.swing.JMenuItem jMenuItemTraitementLineaireMorphologieElementaireErosion;
    private javax.swing.JMenuItem jMenuItemTraitementLineaireMorphologieElementaireFermeture;
    private javax.swing.JMenuItem jMenuItemTraitementLineaireMorphologieElementaireOuverture;
    private javax.swing.JMenu jMenuLineaire;
    private javax.swing.JMenu jMenuLineaireGlobal;
    private javax.swing.JMenu jMenuNouvelle;
    private javax.swing.JMenu jMenuOuvrir;
    private javax.swing.JMenuItem jMenuQuitter;
    private javax.swing.JMenu jMenuTraitement;
    private javax.swing.JMenu jMenuTraitementComplexe;
    private javax.swing.JMenu jMenuTraitementElementaire;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JPanel panelGrid;
    private javax.swing.JPanel panelResult;
    private javax.swing.JLabel resultPanel;
    // End of variables declaration//GEN-END:variables
    
}
